<a href="https://colab.research.google.com/github/jayanithyan/tensor-zero/blob/main/01_linear_algebra/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
student = [5, 85, 8, 72]

print(student)
print(len(student))

[5, 85, 8, 72]
4


In [2]:
import numpy as np

student = np.array([5, 85, 8, 72])

print(student)
print(student.shape)

[ 5 85  8 72]
(4,)


In [5]:
x=np.array([2,4,6])
print(x+2)
print(x*2)

[4 6 8]
[ 4  8 12]


In [6]:
a = np.array([2, 3, 4])
b = np.array([10, 20, 30])

a * b

array([ 20,  60, 120])

In [8]:
x = np.array([2, 3, 4])
w = np.array([0.1, 0.5, 0.2])
result = 0

for i in range(len(x)):
    result += x[i] * w[i]

print(result)

2.5


In [10]:
result = np.dot(x, w)
print(result)

2.5


In [12]:
result = x@w
print(result)

2.5


In [13]:
x = np.array([2, 3, 4])
w = np.array([0.1, 0.5, 0.2])

b = 1

z = x @ w + b

print(z)

3.5


In [14]:
X = np.array([
    [2, 3, 4],
    [5, 7, 2],
    [1, 2, 8],
    [6, 4, 3]
])
print(X.shape)

(4, 3)


In [16]:
W = np.random.randn(3, 5)
X@W

array([[ 6.92463325, -1.47471041, 10.4806101 ,  7.82623997,  9.95172026],
       [ 3.80310474, -5.28746479,  9.0924041 , 13.2907655 , 12.63680829],
       [13.62958506,  0.42962425, 18.08065801,  8.75119824, 14.25270301],
       [ 4.30206903, -5.03433826, 11.89188927, 11.73522012, 12.71079314]])

In [17]:
def matrix_multiply(A, B):
    rows_A = len(A)
    cols_A = len(A[0])

    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
        raise ValueError("Incompatible shapes")

    result = []

    for i in range(rows_A):
        row = []

        for j in range(cols_B):
            value = 0

            for k in range(cols_A):
                value += A[i][k] * B[k][j]

            row.append(value)

        result.append(row)

    return result

In [18]:
A = [
    [1, 2],
    [3, 4]
]

B = [
    [5, 6],
    [7, 8]
]

print(matrix_multiply(A, B))

[[19, 22], [43, 50]]


In [19]:
np.array(A) @ np.array(B)

array([[19, 22],
       [43, 50]])

In [20]:
X = np.array([
    [2, 3, 4],
    [5, 7, 2],
    [1, 2, 8],
    [6, 4, 3]
])

W = np.random.randn(3, 5)

b = np.zeros(5)

Z = X @ W + b

In [21]:
print(X.shape)
print(W.shape)
print(b.shape)
print(Z.shape)

(4, 3)
(3, 5)
(5,)
(4, 5)
